#!/bin/bash

#script que suma dos numeros

# funcion de ayuda

function ayuda(){
cat << DESCRIPCION_AYUDA
$0 NUMERO_1 NUMERO_2
DESCRIPCION
Retorna la suma de NUMERO_1 NUMERO_2
CODIGOS DE RETORNO
1 Si el numero de parametros es distinto de 2
1 Si algun parametro no es un numero
DESCRIPCION_AYUDA
}

function comprobarQueNoEsNumero(){
	if [ -n "$1" \ -a "$1" != "0" \ -a "`echo $1 | awk '{ print $1*1 }'`" != "$1" ];then
		echo "El parametro "$1" no es un numero"
		ayuda

		exit 2
	fi
}

if [ "$#" -ne 2 ];then
	echo "El numero de parametros de ser igual a 2"
fi

comprobarQueNoEsNumero $1
comprobarQueNoEsNumero $2

echo $1 $2 | awk '{ print $1 + $2 }'
