#!/bin/bash

# Script de resta

# Funcion de ayuda
function ayuda() {
cat << AYUDA

Pide ayuda

AYUDA
}

# Funcion que valida si no es numero
function noEsNumero() {

if [ -n "$1"\
	-a "$1" != "0"\
	-a "`echo $1 | awk '{ print $1*1 }'`" != "$1" ];then
	
	echo " El valor ingresadoi 
